name: .NET CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      BUILD_CONFIG: Release
      TEST_PROJECT_PATH: SubsequenceFinder.Tests/SubsequenceFinder.Tests.csproj

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore Dependencies and Build Solution
        run: dotnet build --configuration ${{ env.BUILD_CONFIG }} --no-restore

      - name: Run Unit Tests
        run: dotnet test ${{ env.TEST_PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIG }} --no-build
